### ISSUE TITLE
README for implementation

### ISSUE THREAD

**Issue by dipansh-girdhar** [mhagiwara/xfspell#1]
Hi, 
I'm thinking of using this spell checker/corrector component for medical data. I was hoping if you could add documentation of how to get things working and add any other suggestions if you have. That'd be really helpful. Hoping to hear back from you. 

Thanks.

**Comment by mhagiwara** [comment]
@dipansh-girdhar Thanks, this project is still work in progress (I'm still training a model). I'll update the README and probably upload a blog post detailing how this works and how to create your own if you want.
